services:
  target1:
    build: ./target1
    container_name: ctf-medium-target1
    networks:
      dmz_net_m:
        ipv4_address: 172.22.0.10
      internal_net_m:
        ipv4_address: 172.23.0.10
    ports:
      - "8443:8443"
    restart: unless-stopped

  target2:
    build: ./target2
    container_name: ctf-medium-target2
    networks:
      internal_net_m:
        ipv4_address: 172.23.0.20
    restart: unless-stopped

networks:
  dmz_net_m:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24
  internal_net_m:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.23.0.0/24
